### ISSUE TITLE
Loading sample data - conversationkm-raw container isn't publicly available

### ISSUE THREAD

**Issue by stevelange17** [microsoft/Customer-Service-Conversational-Insights#2]
When trying to load sample data using "deploy_sample_data.ps1", the blob container "https://conversationalinsights.blob.core.windows.net/conversationkm-raw" isn't publicly-available as noted in the video. As a result, I'm not able to load the sample data files from that blob container. 

Any help is appreciated - thanks!

**Comment by ruoccofabrizio** [comment]
modified blob storage source for sample data. Thanks for highlighting it!

**Comment by setiadeepanshu01** [comment]
Hello @ruoccofabrizio and @stevelange17 could you please share the video for this demo, could not find it anywhere?
